name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Set up SonarScanner CLI
        uses: sonarsource/sonar-scanner-cli-action@v1
        with:
          sonar-project-key: dot_net
          sonar-host-url: ${{ secrets.SONAR_HOST_URL }}
          sonar-login: ${{ secrets.SONAR_TOKEN }}
      - name: Build and analyze with dotnet build
        run: |
          cd TaskManagement
          for project in $(find . -name '*.csproj'); do
            dotnet build "$project"
          done
